In [ ]:
import numpy as np
start=int(input("start number"))
end=int(input("end number"))
for num in range(start,end):
  if num>1 :
    for number in range(2,num):
      if (num % number) == 0:
        break
    else:
      print(num)
        

start number10
end number20
11
13
17
19


In [ ]:
import numpy as np
string=input("")
list=string.split()
print(list)
size=len(list)
for i in range (0,size):
  k=0
  for j in range (0,size):
    if list[i] == list[j] :
      k=k+1
      percentage=(k/size)*100
  print(list[i],"==",percentage)


anil sagar anil rohit rohit rohit
['anil', 'sagar', 'anil', 'rohit', 'rohit', 'rohit']
anil == 33.33333333333333
sagar == 16.666666666666664
anil == 33.33333333333333
rohit == 50.0
rohit == 50.0
rohit == 50.0


In [ ]:

import math
def isPerfectSquare(x):
	s = int(math.sqrt(x))
	return s*s == x
def isFibonacci(n):
	return isPerfectSquare(5*n*n + 4) or isPerfectSquare(5*n*n - 4)
i = int(input())
if (isFibonacci(i) == True):
  print(i, "is a Fibonacci Number")
else:
  print(i, "is a not Fibonacci Number ")


11
11 is a not Fibonacci Number 


In [ ]:

def checkDivisibility(n, digit) :
	

	return (digit != 0 and n % digit == 0)
	

def allDigitsDivide( n) :
	
	temp = n
	while (temp > 0) :
		digit = temp % 10
		if ((checkDivisibility(n, digit)) == False) :
			return False

		temp = temp // 10
	
	return True

n=int(input())

if (allDigitsDivide(n)) :
	print("Yes")
else :
	print("No" )
	


128
Yes


In [ ]:
def SplitArray(arr, n, k):
	for i in range(0, k):
		x = arr[0]
		for j in range(0, n-1):
			arr[j] = arr[j + 1]
		
		arr[n-1] = x	
string=input("")
arr=string.split()	
n = len(arr)
position=int(input())
SplitArray(arr, n, position)
for i in range(0, n):
	print(arr[i], end = ' ')

1 2 3 4 5
3
4 5 1 2 3 

In [ ]:
import numpy as np
new_array = np.random.randint(3,10, size=(4,5))
print(new_array)

[[5 3 5 7 5]
 [7 5 5 4 3]
 [4 9 6 6 3]
 [8 9 8 9 6]]


In [ ]:
import numpy as np
new_array = np.random.randint(3,10, size=(4,5))
print(new_array)

In [7]:
import numpy as np
fvalues = [0, 12, 45.21, 34, 99.91, 32]
F = np.array(fvalues)
print("Fahrenheit degrees:")
print(F)
print("Centigrade degrees:")
print(np.round((5*F/9 - 5*32/9),2))


Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91 32.  ]
Centigrade degrees:
[-17.78 -11.11   7.34   1.11  37.73   0.  ]


In [13]:
import numpy as np    
x = np.array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
print("\ndimensions:")
print(x.ndim)
print("elements:")
print(x.size)
print("Number of bytes")
print(x.itemsize) 



dimensions:
2
elements:
24
Number of bytes
8


In [15]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print(arra_data)
print("\n 3rd and 4th elements of the 1&2 rows ")
print(arra_data[0:2, 2:4])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 3rd and 4th elements of the 1&2 rows 
[[2 3]
 [6 7]]
