In [ ]:
import pandas as pd
import numpy as np
import scipy as sci

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/machinelearning/nba for lab4.csv")

In [ ]:
df.sample(10)

Name                   Team  Number Position   Age Height  \
82     Draymond Green  Golden State Warriors    23.0       PF  26.0    6-7   
9        Marcus Smart         Boston Celtics    36.0       PG  22.0    6-4   
247        Sam Dekker        Houston Rockets     7.0       SF  22.0    6-9   
68     Lucas Nogueira        Toronto Raptors    92.0        C  23.0    7-0   
375      Nene Hilario     Washington Wizards    42.0        C  33.0   6-11   
126      John Jenkins           Phoenix Suns    23.0       SG  25.0    6-4   
342      Gerald Green             Miami Heat    14.0       SF  30.0    6-7   
96      Blake Griffin   Los Angeles Clippers    32.0       PF  27.0   6-10   
35   Cleanthony Early        New York Knicks    11.0       SF  25.0    6-8   
337   Marvin Williams      Charlotte Hornets     2.0       PF  29.0    6-9   

     Weight         College      Salary  
82    230.0  Michigan State  14260870.0  
9     220.0  Oklahoma State   3431040.0  
247   230.0       Wisconsin   1646400.0  
68    220.0             NaN   1842000.0  
375   250.0             NaN  13000000.0  
126   215.0      Vanderbilt    981348.0  
342   205.0             NaN    947276.0  
96    251.0        Oklahoma  18907726.0  
35    210.0   Wichita State    845059.0  
337   237.0  North Carolina   7000000.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      457 non-null    object 
 1   Team      457 non-null    object 
 2   Number    457 non-null    float64
 3   Position  457 non-null    object 
 4   Age       457 non-null    float64
 5   Height    457 non-null    object 
 6   Weight    457 non-null    float64
 7   College   373 non-null    object 
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB


In [ ]:
df.describe()

Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [ ]:
df.describe(include=['object'])

Name                  Team Position Height   College
count             457                   457      457    457       373
unique            457                    30        5     18       118
top     Avery Bradley  New Orleans Pelicans       SG    6-9  Kentucky
freq                1                    19      102     59        22

In [ ]:
df.isna().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

**Handling Missing Values: 1. Deleting only the rows/columns with missing values**

In [ ]:
df1 = df.copy()
df1 = df1.dropna(axis=0)
df1.isna().sum()

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [ ]:
df1.shape

(364, 9)

**Handling Missing Values: 2. Data Imputing missing values with Mean/Median/Mode**


In [ ]:
df2 = df.copy()
df2['Salary']=df2['Salary'].fillna(df2['Salary'].mean())
df2.dropna(axis=0,inplace=True, how='any')
df2.isna().sum()

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [ ]:
df2.shape

(373, 9)

**Handling Missing Values: 3. Simple Imputer**


In [ ]:
from sklearn.impute import SimpleImputer
df3 = df.copy()
df3['Salary_Missing'] = df3['Salary'].isnull()
df3.dropna(axis=0,inplace=True, how='any', subset=['Name', 'Team', 'Position', 'Height', 'College'])

my_imputer = SimpleImputer(missing_values=np.NaN, strategy = 'mean') # the imputation strategy can be 'mean'/'median'/'most_frequent'/'constant'
new_data = my_imputer.fit_transform(df3['Salary'].values.reshape(-1,1))[:,0]
df3.Salary = new_data

df3.isnull().sum()

Name              0
Team              0
Number            0
Position          0
Age               0
Height            0
Weight            0
College           0
Salary            0
Salary_Missing    0
dtype: int64

In [ ]:
df3.sample(10)

Name                    Team  Number Position   Age Height  \
219     Khris Middleton         Milwaukee Bucks    22.0       SG  24.0    6-8   
352     Justise Winslow              Miami Heat    20.0       SF  20.0    6-7   
327    Tyler Hansbrough       Charlotte Hornets    50.0       PF  30.0    6-9   
401          Tyus Jones  Minnesota Timberwolves     1.0       PG  20.0    6-2   
240  Charlie Villanueva        Dallas Mavericks     3.0       PF  31.0   6-11   
420       Nazr Mohammed   Oklahoma City Thunder    13.0        C  38.0   6-10   
144          Seth Curry        Sacramento Kings    30.0       SG  25.0    6-2   
137      James Anderson        Sacramento Kings     5.0       SG  27.0    6-6   
194       Marcus Morris         Detroit Pistons    13.0       PF  26.0    6-9   
366      Nikola Vucevic           Orlando Magic     9.0        C  25.0    7-0   

     Weight         College      Salary  Salary_Missing  
219   234.0       Texas A&M  14700000.0           False  
352   225.0            Duke   2481720.0           False  
327   250.0  North Carolina    947276.0           False  
401   195.0            Duke   1282080.0           False  
240   232.0     Connecticut    947276.0           False  
420   250.0        Kentucky    222888.0           False  
144   185.0            Duke    947276.0           False  
137   213.0  Oklahoma State   1015421.0           False  
194   235.0          Kansas   5000000.0           False  
366   260.0             USC  11250000.0           False

**Formatting data**

In [ ]:
df3['Height_In_Inches'] = df3['Height'].apply(lambda x: 12*int(x[:1]) + int(x[2:]))
df3.drop('Height', inplace=True, axis=1)

In [ ]:
df3.sample(5)

Name                    Team  Number Position   Age  Weight  \
421  Anthony Morrow   Oklahoma City Thunder     2.0       SG  30.0   210.0   
71    Terrence Ross         Toronto Raptors    31.0       SF  25.0   195.0   
430    Allen Crabbe  Portland Trail Blazers    23.0       SG  24.0   210.0   
346  Josh McRoberts              Miami Heat     4.0       PF  29.0   240.0   
167   Channing Frye     Cleveland Cavaliers     9.0       PF  33.0   255.0   

          College     Salary  Salary_Missing  Height_In_Inches  
421  Georgia Tech  3344000.0           False                77  
71     Washington  3553917.0           False                79  
430    California   947276.0           False                78  
346          Duke  5543725.0           False                82  
167       Arizona  8193029.0           False                83

**Removing Duplicates**

In [ ]:
df4 = df3.copy()
df4.duplicated().sum()

0

In [ ]:
# Duplicating the instances
df4 = pd.concat([df4]*2, ignore_index=True)


In [ ]:
df4.duplicated().sum()

373

In [ ]:
df4[df4.duplicated()]

Name            Team  Number Position   Age  Weight  \
373  Avery Bradley  Boston Celtics     0.0       PG  25.0   180.0   
374    Jae Crowder  Boston Celtics    99.0       SF  25.0   235.0   
375   John Holland  Boston Celtics    30.0       SG  27.0   205.0   
376    R.J. Hunter  Boston Celtics    28.0       SG  22.0   185.0   
377  Jordan Mickey  Boston Celtics    55.0       PF  21.0   235.0   
..             ...             ...     ...      ...   ...     ...   
741    Rodney Hood       Utah Jazz     5.0       SG  23.0   206.0   
742  Chris Johnson       Utah Jazz    23.0       SF  26.0   206.0   
743     Trey Lyles       Utah Jazz    41.0       PF  20.0   234.0   
744   Shelvin Mack       Utah Jazz     8.0       PG  26.0   203.0   
745    Jeff Withey       Utah Jazz    24.0        C  26.0   231.0   

               College        Salary  Salary_Missing  Height_In_Inches  
373              Texas  7.730337e+06           False                74  
374          Marquette  6.796117e+06           False                78  
375  Boston University  4.620311e+06            True                77  
376      Georgia State  1.148640e+06           False                77  
377                LSU  1.170960e+06           False                80  
..                 ...           ...             ...               ...  
741               Duke  1.348440e+06           False                80  
742             Dayton  9.813480e+05           False                78  
743           Kentucky  2.239800e+06           False                82  
744             Butler  2.433333e+06           False                75  
745             Kansas  9.472760e+05           False                84  

[373 rows x 10 columns]

In [ ]:
df4.drop_duplicates(keep = 'first', inplace = True) # keep may be one of the 'first'/'last'/False

In [ ]:
df4.duplicated().sum()

0

**Encoding the categorical data**

In [ ]:
# Label Encoding of Name, which is not necessary in reality

from sklearn import preprocessing
  
label_encoder = preprocessing.LabelEncoder()
  
df4['Name']= label_encoder.fit_transform(df4['Name'])
df4['College']= label_encoder.fit_transform(df4['College'])

df4.sample(10)

Name                   Team  Number Position   Age  Weight  College  \
84    284   Los Angeles Clippers    34.0       SF  38.0   235.0       43   
307    98     Washington Wizards    90.0       PF  34.0   250.0       43   
244   194   New Orleans Pelicans    11.0       PG  25.0   205.0       96   
159    78        Detroit Pistons     6.0       SF  23.0   205.0      102   
47    140     Philadelphia 76ers     8.0        C  20.0   275.0       26   
91    184     Los Angeles Lakers     6.0       PG  24.0   194.0       60   
1     139         Boston Celtics    99.0       SF  25.0   235.0       52   
128   169          Chicago Bulls    21.0       SG  26.0   220.0       52   
335   266  Oklahoma City Thunder     4.0       PF  35.0   255.0       43   
70    148  Golden State Warriors    20.0       SF  23.0   240.0       66   

         Salary  Salary_Missing  Height_In_Inches  
84    3376000.0           False                79  
307   3300000.0           False                82  
244  10595507.0           False                76  
159    600000.0           False                78  
47    4582680.0           False                83  
91     845059.0           False                77  
1     6796117.0           False                78  
128  16407500.0           False                79  
335   3750000.0           False                82  
70     845059.0           False                81

In [ ]:
# Ordinal Encoding

from sklearn.preprocessing import OrdinalEncoder
ord1 = OrdinalEncoder()

ord1.fit([df4['Position']])

df4['Position'] = ord1.fit_transform(df4[['Position']])
df4.sample(10)

Name                 Team  Number  Position   Age  Weight  College  \
131   197        Chicago Bulls     7.0       4.0  27.0   185.0      107   
15    305        Brooklyn Nets    24.0       4.0  21.0   220.0        1   
155   208      Detroit Pistons     5.0       4.0  23.0   205.0       32   
311   275   Washington Wizards    22.0       3.0  23.0   198.0       31   
139    53  Cleveland Cavaliers     9.0       1.0  33.0   255.0        1   
39    300   Philadelphia 76ers    33.0       3.0  25.0   215.0       92   
189   122      Milwaukee Bucks    21.0       2.0  29.0   217.0       54   
211   334      Houston Rockets     6.0       1.0  24.0   252.0       45   
132    96        Chicago Bulls     3.0       3.0  24.0   225.0       21   
282    57           Miami Heat     1.0       1.0  32.0   235.0       34   

         Salary  Salary_Missing  Height_In_Inches  
131    947276.0           False                78  
15    1335480.0           False                79  
155   2891760.0           False                77  
311   4662960.0           False                80  
139   8193029.0           False                83  
39    1000000.0           False                81  
189   6600000.0           False                78  
211   2489530.0           False                81  
132   2380440.0           False                80  
282  22192730.0           False                83

In [ ]:
# One_hot Encoding
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()

enc = enc.fit_transform(df4[['Team']]).toarray()
encoded_colm = pd.DataFrame(enc)

df4 = pd.concat([df4, encoded_colm], axis = 1)

df4 = df4.drop(['Team'], axis = 1)
df4.head(10)

Name  Number  Position   Age  Weight  College        Salary  \
0    29     0.0       2.0  25.0   180.0       93  7.730337e+06   
1   139    99.0       3.0  25.0   235.0       52  6.796117e+06   
2   177    30.0       4.0  27.0   205.0        8  4.620311e+06   
3   288    28.0       4.0  22.0   185.0       33  1.148640e+06   
4   189    55.0       1.0  21.0   235.0       46  1.170960e+06   
5   202    41.0       0.0  25.0   238.0       35  2.165160e+06   
6   336    12.0       2.0  22.0   190.0       51  1.824360e+06   
7   238    36.0       2.0  22.0   220.0       72  3.431040e+06   
8   152     7.0       0.0  24.0   260.0       70  2.569260e+06   
9   130     4.0       2.0  27.0   185.0      107  6.912869e+06   

   Salary_Missing  Height_In_Inches    0  ...   20   21   22   23   24   25  \
0           False                74  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   
1           False                78  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   
2            True                77  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   
3           False                77  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   
4           False                80  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   
5           False                84  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   
6           False                74  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   
7           False                76  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   
8           False                81  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   
9           False                69  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   

    26   27   28   29  
0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  
5  0.0  0.0  0.0  0.0  
6  0.0  0.0  0.0  0.0  
7  0.0  0.0  0.0  0.0  
8  0.0  0.0  0.0  0.0  
9  0.0  0.0  0.0  0.0  

[10 rows x 39 columns]

In [ ]:
df4.drop(['Salary_Missing'], axis=1, inplace=True)

In [ ]:
df5 = df4.pop('Salary') 
df4['Salary']=df5
df4.sample(10)

Name  Number  Position   Age  Weight  College  Height_In_Inches    0  \
263   219    26.0       4.0  35.0   212.0       21                79  1.0   
272     2     9.0       4.0  21.0   210.0       45                78  0.0   
14    363    21.0       4.0  28.0   200.0       66                76  0.0   
370   350    41.0       1.0  20.0   234.0       45                82  0.0   
192   132     5.0       2.0  31.0   185.0       68                72  0.0   
212   199    32.0       4.0  23.0   205.0       16                78  0.0   
145   210     0.0       1.0  27.0   251.0       96                82  0.0   
284   360    40.0       1.0  36.0   235.0       28                80  0.0   
172   117    40.0       4.0  22.0   222.0       57                79  0.0   
4     189    55.0       1.0  21.0   235.0       46                80  0.0   

       1    2  ...   21   22   23   24   25   26   27   28   29      Salary  
263  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   5746479.0  
272  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    525093.0  
14   0.0  1.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   1500000.0  
370  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   2239800.0  
192  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   4290000.0  
212  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   3189794.0  
145  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  19689000.0  
284  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   2854940.0  
172  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   1100000.0  
4    1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   1170960.0  

[10 rows x 38 columns]

**Feature Scaling - MinMaxScaler**

In [ ]:
from sklearn.preprocessing import MinMaxScaler
array = df4.values
x=array[:,0:37]
y=array[:,37]
scaler=MinMaxScaler(feature_range=(0,1))
rescaledX=scaler.fit_transform(x)
np.set_printoptions(precision=3)
rescaledX[0:5,:]


array([[0.078, 0.   , 0.5  , 0.286, 0.161, 0.795, 0.294, 0.   , 1.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.374, 1.   , 0.75 , 0.286, 0.627, 0.444, 0.529, 0.   , 1.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.476, 0.303, 1.   , 0.381, 0.373, 0.068, 0.471, 0.   , 1.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.774, 0.283, 1.   , 0.143, 0.203, 0.282, 0.471, 0.   , 1.   ,
        0.   , 0.   , 0.   , 

**Feature Scaling - StandardScaler**

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler().fit(x)
rescaledX=scaler.transform(x)
rescaledX[0:5,:]

array([[-1.458, -1.13 , -0.132, -0.388, -1.579,  1.09 , -1.462, -0.174,
         5.262, -0.19 , -0.19 , -0.182, -0.182, -0.182, -0.157, -0.205,
        -0.182, -0.174, -0.182, -0.197, -0.182, -0.219, -0.174, -0.197,
        -0.157, -0.212, -0.174, -0.197, -0.166, -0.205, -0.19 , -0.205,
        -0.19 , -0.174, -0.166, -0.166, -0.19 ],
       [-0.436,  5.49 ,  0.601, -0.388,  0.612, -0.171, -0.253, -0.174,
         5.262, -0.19 , -0.19 , -0.182, -0.182, -0.182, -0.157, -0.205,
        -0.182, -0.174, -0.182, -0.197, -0.182, -0.219, -0.174, -0.197,
        -0.157, -0.212, -0.174, -0.197, -0.166, -0.205, -0.19 , -0.205,
        -0.19 , -0.174, -0.166, -0.166, -0.19 ],
       [-0.084,  0.876,  1.334,  0.083, -0.583, -1.525, -0.555, -0.174,
         5.262, -0.19 , -0.19 , -0.182, -0.182, -0.182, -0.157, -0.205,
        -0.182, -0.174, -0.182, -0.197, -0.182, -0.219, -0.174, -0.197,
        -0.157, -0.212, -0.174, -0.197, -0.166, -0.205, -0.19 , -0.205,
        -0.19 , -0.174, -0.166, -0.166

**Feature Scaling - Normalizer**

In [ ]:
from sklearn.preprocessing import Normalizer
scaler=Normalizer().fit(x)
normalizedX=scaler.transform(x)
normalizedX[0:5,:]

array([[0.132, 0.   , 0.009, 0.114, 0.822, 0.425, 0.338, 0.   , 0.005,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.454, 0.323, 0.01 , 0.082, 0.767, 0.17 , 0.255, 0.   , 0.003,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.622, 0.105, 0.014, 0.095, 0.72 , 0.028, 0.271, 0.   , 0.004,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.813, 0.079, 0.011, 0.062, 0.522, 0.093, 0.217, 0.   , 0.003,
        0.   , 0.   , 0.   , 

**Binarizing the data**

In [ ]:
# Binarizing Data using Binarizer
from sklearn.preprocessing import Binarizer
binarizer=Binarizer(threshold=0.0).fit(x)
binaryX=binarizer.transform(x)
binaryX[0:5,:]


array([[1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.]])

**Splitting the Data to Training and Test Sets**

In [ ]:
# split a dataset into train and test sets
from sklearn.model_selection import train_test_split


# split into train test sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.30)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(261, 37) (112, 37) (261,) (112,)


In [ ]:
X_train

array([[109.,  25.,   1., ...,   0.,   0.,   0.],
       [ 21.,   3.,   3., ...,   0.,   0.,   0.],
       [152.,   7.,   0., ...,   0.,   0.,   0.],
       ...,
       [350.,  41.,   1., ...,   0.,   1.,   0.],
       [288.,  28.,   4., ...,   0.,   0.,   0.],
       [264.,  13.,   0., ...,   0.,   0.,   0.]])